add:chatwork-er図
nanakusa27/quelcode-db pull request #1
Opened 2020-06-15 06:10 UTC by nanakusa27

データベース課題１、ER図

2020-06-15 07:14 UTC, piasoratech requested changes
以下の指摘があるので確認と修正をお願いします。
- テーブル名は複数形にしてください。
- 今回中間テーブルを作るのはuser-chatroomの部分だけでOKです。
- `created_at`と`update_at`の単語時系列を合わせましょう。(過去形が良いです)
- ファイル用のテーブルはわけなくて大丈夫です。今回は`chat`テーブルでファイル名だけを持つ仕様にしてください。
- フラグ系のカラムは`is_xxx`の形にしましょう
- `user`テーブルが要件を満たせていません。
- `chat`テーブルに同じ名前のカラムが存在しています。
- 更新日時や作成日時のカラムの後ろにカラムがないようにしましょう。

2020-06-15 08:31 UTC, nanakusa27 commented
- テーブル名を複数形に変更
- task_menberの中間テーブルの削除
- 単語時系列をあわせました。
- ファイル用のテーブルの削除、chatsテーブルにfile_name追加
- フラグ系カラムの名称変更
- usersテーブルにtel_work, tel_mobileの追加
- chatsテーブルの重複カラムの解消
- 更新日時や作成日時のカラムの位置確認しました。

2020-06-15 08:47 UTC, piasoratech requested changes
以下の内容を確認、修正をお願いします。
- `tasks`テーブルが要件を満たせていないので、確認をお願いします。
- `tasks`テーブルの`is_complete`も単語の時系列を合わせましょう
- `chatrooms`テーブルの`is_file_send`はこの命名だとtrueの時ファイルを送信していいのか、送信を禁止されているのか分からないので、分かるような命名にしましょう。

2020-06-16 04:02 UTC, himaru-jp commented
以下の内容を確認、修正をお願いします。
- `tasks `テーブルの`manager`ですが、「担当者」なのか「割り当てた人」なのか分かりづらいため、より明確な命名にしましょう
- `tasks `テーブルの`manager`ですが、タスク内容と分かるようなより明確な命名にしましょう

2020-06-16 07:12 UTC, himaru-jp approved these changes
レビューOKです。

参考までに。
英単語としてはstaffでもギリギリニュアンスとしては通じますが、日本人の一般的なイメージが定着している単語は用法の注意が必要です。
今回であれば、「担当」とか「割り当て」などの日本語を連想する単語を用いるとよりいいと思います。
またIDが入る場合は、xxxx_user_idのような形式にすると、中に入っているものが連想しやすくなります。

2020-06-16 07:27 UTC, merged