DB定義書、DDL文提出
nanakusa27/quelcode-db pull request #2
Opened 2020-06-17 03:22 UTC by nanakusa27

DB課題２

2020-06-17 04:30 UTC, piasoratech requested changes
データベース定義書の指摘事項
- `chatrooms`の`is_send_permission`は名前をもう少し考えてみましょう。物理名を見ただけで`true`であればどんな状態、`false`であればどんな状態かわかる名前にするのが理想形です。(`is_deleted`なら`true`だと削除済みというのがすぐわかるみたいな感じです。)
- `chatrooms`の更新系カラムの物理名の時系列が過去になっていないです。
- `tasks`の担当ユーザーIDの物理名に・が入ってしまっています。(もし、そちらの環境で確認できない場合は一度消してもう一度入力し直せば直るかと思います。)
![image](https://user-images.githubusercontent.com/57445698/84855285-b36fee80-b09e-11ea-9566-f53006914140.png)

- `chat_members`のテーブル名がtypoしています。

再提出前に定義書とDDL文が合致しているかもう一度確認をして下さい。

2020-06-17 04:30 UTC, piasoratech commented on db/db-challenge2/chatwork.sql
> +    email VARCHAR(100) UNIQUE NOT NULL,
今回要件にメールアドレスをユニークにするというのは含めていないので、ユニーク制約を削除してください。
要件に含んでいない理由として、論理削除でデータを扱っているというのがあります。
例えばこのサービスに登録をしたユーザーが退会処理をせずにメールアドレスを放棄してその後、別のユーザーが全く同じメールアドレスを取得して登録をしようとするとその人は登録ができなくなってしまうといったような事象が発生してしまうことが考えられます。

2020-06-17 04:34 UTC, nanakusa27 commented on db/db-challenge2/chatwork.sql
> +    email VARCHAR(100) UNIQUE NOT NULL,
なるほど！考えが及んでませんでした。
勉強になります！

2020-06-17 06:45 UTC, piasoratech requested changes
データベース定義書指摘事項
- 送信許可フラグの命名は以前よりも良くなりましたが、`is_can_xxxx`という命名はあまりメジャーではないです。英語では動詞+ableで～が可能なといった表現ができるので`is_sendable`などとしたほうがより良いかと思います。

2020-06-17 06:45 UTC, piasoratech commented on db/db-challenge2/chatwork.sql
> +    user_id INT(11) NOT NULL REFERENCES users(users),
外部キー制約の記載が間違っているので修正しましょう

2020-06-18 02:08 UTC, piasoratech requested changes
コメントしたので確認をお願いします。
あと、指摘を忘れていましたが各テーブルの作成者IDと更新者IDはすべて外部キー制約をつけておきましょう。
(課題1では省略していいこととしていたので、指摘がなかったかと思います。)

2020-06-18 02:08 UTC, piasoratech commented on db/db-challenge2/chatwork.sql
> +    is_send_able TINYINT(1) NOT NULL DEFAULT 1,
`is_sendable`が正しいです。
エクセルのほうの定義書も修正をしてください。

2020-06-18 03:19 UTC, piasoratech requested changes
指摘が漏れていて申し訳ないのですがデータベース定義書の`chat_members`テーブルにPK指定が書いていないので追加しましょう

2020-06-18 03:32 UTC, piasoratech approved these changes
OKです！次に行きましょう！

2020-06-18 03:55 UTC, merged