Feature/db challenge3
nanakusa27/quelcode-db pull request #3
Opened 2020-06-18 10:56 UTC by nanakusa27

DB課題３

2020-06-18 10:57 UTC, nanakusa27 commented
DB課題３
問題番号001～005

2020-06-19 02:16 UTC, piasoratech requested changes
提出形式が指示した形と違うので再提出してください

2020-06-19 03:49 UTC, piasoratech requested changes
コメントしたので確認をお願いします。

2020-06-19 03:49 UTC, piasoratech commented on db/db-challenge3/db-002/db-002.sql
> +('ぱんだ', 'フレームワーク', 0, DEFAULT, DEFAULT, 5, '2020/04/23 18:14:28', 7, '2020/04/24 20:33:06'),
`about`の内容が違います

2020-06-19 05:01 UTC, piasoratech reviewed
No001～005はOKです

2020-06-19 08:16 UTC, piasoratech requested changes
コメントしたので確認をお願いします。

2020-06-19 08:16 UTC, piasoratech commented on db/db-challenge3/db-007/db-007.sql
> +SELECT chatroom_id, chatroom_name, about, is_sendable, is_deleted, created_at, created_by_user_id, updated_at, updated_by_user_id, CASE WHEN 1 = is_sendable THEN '許可' ELSE '禁止' END
`1 = is_sendable`と書くよりは`is_sendable = 1`のほうが一般的ですかね…
WHERE句の条件の書き方と変わらないです

2020-06-19 08:35 UTC, piasoratech reviewed
No006～010もOKです
次に進みましょう！

2020-06-22 02:50 UTC, piasoratech approved these changes
ＯＫです！お疲れ様でした！

2020-10-23 00:38 UTC, merged